name: Test

on: [ push, pull_request ]

jobs:
  test:

    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: |
          cd symfony
          composer validate --strict

      - name: Parse Git short hash
        run: echo "git_short_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          cd symfony
          php7.4 -f /usr/bin/composer install
          php7.4 -f /usr/bin/composer dump-autoload -o
          cd client
          yarn install

      - name: Install OrangeHRM
        run: |
          php7.4 installer/cli_install.php 0
          php7.4 devTools/general/create-test-db.php root

      - name: Run Jest
        run: |
          cd symfony/client
          yarn test:unit --coverage

      - name: Run test
        run: |
          XDEBUG_MODE=coverage ./symfony/vendor/bin/phpunit --coverage-html coverage -d memory_limit=1G
          tar cf - coverage/ | xz -z - > coverage.tar.xz

      - name: Upload jest coverage
        uses: actions/upload-artifact@v2
        with:
          name: jest-coverage
          path: symfony/client/coverage

      - name: Upload phpunit coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.tar.xz

  composer_v1_check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use composer v1
        run: sudo composer self-update --1

      - name: Validate composer.json and composer.lock
        run: |
          cd symfony
          php7.4 -f /usr/bin/composer validate --strict
          php8.0 -f /usr/bin/composer validate --strict
          php8.1 -f /usr/bin/composer validate --strict

      - name: Install depandancies on PHP 7.4
        run: |
          cd symfony
          php7.4 -f /usr/bin/composer install
          php7.4 -f /usr/bin/composer dump-autoload -o

      - name: Install depandancies on PHP 8.0
        run: |
          cd symfony
          rm -rf vendor
          php8.0 -f /usr/bin/composer install
          php8.0 -f /usr/bin/composer dump-autoload -o
